### ISSUE TITLE
Extension priorities are lost by the WhiteboardFeature

### ISSUE THREAD

**Issue by timothyjward** [geckoprojects-org/org.gecko.jaxrs.whiteboard#17]
Whiteboard extensions are supposed to be ordered as per [section 151.5.2](http://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.jaxrs.html#d0e133578) however the feature loses track of both

1. The `@Priority` annotation (found by looking up a service instance)
2. The service ranking of the whiteboard service.

The extensions must be registered with their priority set (the `Map<Class<?>, Integer>` version of the `register` method), and also registered in the correct order (Jersey uses registration order when priorities are the same.

**Comment by maho7791** [comment]
I already have a version that takes care of the service rank. But Jersey registers all extension for that features in a map, where the key is the instance class. which brings us to the situation, that the second extension overwrites the first.
I beleive we have to register each extension in an own feature, where we again have to use bytebuddy to create a feature proxy, because also, jersey registers all feature in a map with the key is the class :-(
